export const types = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  SIGNUP_REQUEST: 'SIGNUP_REQUEST',
  GET_TOKEN_REQ: 'GET_TOKEN_REQ',
  GET_TOKEN_RES: 'GET_TOKEN_RES',
  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  DELETE_REQUEST: 'DELETE_REQUEST',
  UPDATE_USER_REQUEST: 'UPDATE_USER_REQUEST',
};
